### ISSUE TITLE
run out of memory

### ISSUE THREAD

**Issue by siyoooooo** [jacobgil/pytorch-tensor-decompositions#13]
Thank you for sharing your code on GitHub.In the process of running the code (without changing the code logic and parameters), in the process of using CP decomposition to get a new convolutional layer and replacing the original convolutional layer of the network, due to the excessive number of parameters in the decomposition process.
 I used 720G of memory, but still could only decompose to the eighth layer, and then the process would be killed due to insufficient memory. Is this normal? What should I do if I can't add more memory?

**Comment by miladdona** [comment]
I think the problem is related to the tensorly library to decompose tensor in this line:
parafac(layer.weight.data, rank=rank, init='svd')

I think you can fix it if you change **init='svd'** to **init='random'**

**Comment by siyoooooo** [comment]
@miladdona Thank you so much for your help and reply! It's been very useful to me.
