### ISSUE TITLE
Channel mismatches

### ISSUE THREAD

**Issue by chowkamlee81** [jacobgil/pytorch-tensor-decompositions#3]
Hi ,

Gone thru your code. Great work and encouraging for the rest of the people to work on tensor decomposition. I had a  doubt

Since this algorithm works layer  by layer by decomposition of channels. Every layer number of channel input and output will be reduced.
For next successive layer, If Prev_OUTPUT_Channel != Curr_INPUT_Channel, how coupling is done out?
Kindly help me to understand

**Comment by jacobgil** [comment]
Hi,

Each layer will be decomposed into a block of several layers.
The number of input channels to the new block, will be the number of input channels to the original layer.
The number of output channels from the new block, will be the number of output channels from the original layer.

The reduction is done in the body of the block, but the input/output does not change (unlike in pruning for example).

Does this answer the question?

**Comment by chowkamlee81** [comment]
Sounds good for me . Thanks for making me to understand
